// <auto-generated />
using System;
using MediaPlatform.Storing.Databases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MediaPlatform.Storing.Migrations
{
    [DbContext(typeof(MediaPlatformDbContext))]
    [Migration("20200406204141_testmigration")]
    partial class testmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MediaPlatform.Domain.Models.Community", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Community");

                    b.HasData(
                        new
                        {
                            ID = 637217845008472534L,
                            Name = "Random Community"
                        });
                });

            modelBuilder.Entity("MediaPlatform.Domain.Models.User", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = 637217845008457779L,
                            Name = "Demi Demi",
                            Password = "12345",
                            Username = "demi"
                        },
                        new
                        {
                            ID = 637217845008458692L,
                            Name = "Jesus",
                            Password = "Password12345",
                            Username = "jesus"
                        },
                        new
                        {
                            ID = 637217845008458724L,
                            Name = "George",
                            Password = "password",
                            Username = "george"
                        },
                        new
                        {
                            ID = 637217845008458729L,
                            Name = "Jeremy",
                            Password = "12345",
                            Username = "jeremy"
                        });
                });

            modelBuilder.Entity("MediaPlatform.Domain.Models.Video", b =>
                {
                    b.Property<long>("ID")
                        .HasColumnType("bigint");

                    b.Property<long?>("CommunityID")
                        .HasColumnType("bigint");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("URL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UploadedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("UserID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("CommunityID");

                    b.HasIndex("UserID");

                    b.ToTable("Video");

                    b.HasData(
                        new
                        {
                            ID = 637217845008470452L,
                            Duration = 31L,
                            Title = "Tough Time Never Last, Only Tough People Last",
                            URL = "https://www.youtube.com/embed/1puR8jGK03A",
                            UploadedBy = "Demi Demi"
                        },
                        new
                        {
                            ID = 637217845008471467L,
                            Duration = 247L,
                            Title = "Birds are not real",
                            URL = "https://www.youtube.com/embed/l30_APBNPXg",
                            UploadedBy = "George"
                        },
                        new
                        {
                            ID = 637217845008471514L,
                            Duration = 552L,
                            Title = "Americans brace for possible approach of coronavirus peak",
                            URL = "https://www.youtube.com/embed/MwaK-SmcIx0",
                            UploadedBy = "Jeremy"
                        },
                        new
                        {
                            ID = 637217845008471519L,
                            Duration = 1343L,
                            Title = "Watch Elon Musk announce the Tesla Cybertruck in 14 minutes",
                            URL = "https://www.youtube.com/embed/464puoD09dM",
                            UploadedBy = "Jesus"
                        },
                        new
                        {
                            ID = 637217845008471525L,
                            Duration = 332L,
                            Title = "Rick Astley - Never Gonna Give You up (video)",
                            URL = "https://www.youtube.com/embed/dQw4w9WgXcQ",
                            UploadedBy = "George"
                        },
                        new
                        {
                            ID = 637217845008471531L,
                            Duration = 322L,
                            Title = "The Kooks - Naive",
                            URL = "https://www.youtube.com/embed/jkaMiaRLgvY",
                            UploadedBy = " George"
                        },
                        new
                        {
                            ID = 637217845008471536L,
                            Duration = 535L,
                            Title = "Gladiator Opening Scene(Part 1)",
                            URL = "https://www.youtube.com/embed/yXiSp9aJYN4",
                            UploadedBy = "Jeremy"
                        },
                        new
                        {
                            ID = 637217845008471542L,
                            Duration = 428L,
                            Title = "Harry Potter and the Deathly Hallows part 2 - Snape's memories part 2 (HD)",
                            URL = "https://www.youtube.com/embed/iqyf-kJWwIg",
                            UploadedBy = "Jesus"
                        },
                        new
                        {
                            ID = 637217845008471547L,
                            Duration = 3109L,
                            Title = "Shaq Tries to Not Make a Face While Eating Spicy Wings | Hot Ones",
                            URL = "https://www.youtube.com/embed/_sZH-psg9yE",
                            UploadedBy = "George"
                        },
                        new
                        {
                            ID = 637217845008471552L,
                            Duration = 1336L,
                            Title = "Engine Placement EXPLAINED",
                            URL = "https://www.youtube.com/embed/SiOSbHo2dvk",
                            UploadedBy = "Jesus"
                        });
                });

            modelBuilder.Entity("MediaPlatform.Domain.Models.Community", b =>
                {
                    b.HasOne("MediaPlatform.Domain.Models.User", null)
                        .WithMany("Communities")
                        .HasForeignKey("UserID");
                });

            modelBuilder.Entity("MediaPlatform.Domain.Models.Video", b =>
                {
                    b.HasOne("MediaPlatform.Domain.Models.Community", "Community")
                        .WithMany("Videos")
                        .HasForeignKey("CommunityID");

                    b.HasOne("MediaPlatform.Domain.Models.User", null)
                        .WithMany("Videos")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
